service: basic-serverless-lambda-python

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-central-1

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  theLambda:
    name: Logistics-Reports
    handler: main.lambda_handler
    description: XYZ
    timeout: 900 # seconds
    memorySize: 500 # mb
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"
